#file: noinspection SpellCheckingInspection
name: Checks

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  SSH_PUB_KEY:
    ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKzKKT5xCssZ38UI5VWaPOqW3ldVsg/0tDceTrCFnsd3 github.action@antoinebellanger.fr

jobs:
  compile:
    if: github.repository_owner == 'dawpitech'
    runs-on: ubuntu-latest
    container: epitechcontent/epitest-docker

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
          fetch-depth: '0'

      - name: Compile
        run: cmake -S . -B build && cmake --build build

  trigger-submodules-update:
    runs-on: ubuntu-latest
    needs: compile
    steps:
      - name: Trigger Main Repository CI/CD
        if: success()
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.MAIN_REPO_TOKEN }}" \
            -H "Accept: application/vnd.github.everest-preview+json" \
            https://api.github.com/repos/Dawoox/main-repo/dispatches \
            -d '{"event_type": "update_submodule"}'
